---
title: "Tidy Tuesday Penguins"
output: html_notebook
---

```{r}
# Packages

library(tidytuesdayR)
library(tidyverse)
library(ggplot2)

```


```{r}
tuesdata <- tidytuesdayR::tt_load('2020-07-28')

penguins <- tuesdata$penguins
```

```{r}
penguins %>% ggplot(aes(x = bill_length_mm, 
                        y = bill_depth_mm, 
                        color = species, 
                        shape = island)) +
  geom_point(na.rm = TRUE) +
  scale_color_brewer(palette = "Set1") +
  theme_bw()
```

```{r}
penguins %>% ggplot(aes(x = flipper_length_mm,
                        y = body_mass_g,
                        color = species,
                        shape = sex)) +
  geom_point(na.rm = TRUE) +
  scale_color_brewer(palette = "Set1") +
  theme_bw()
```

```{r}
penguins %>% ggplot(aes(x = island, fill = species)) +
  geom_bar(position = "dodge") + 
  scale_fill_brewer(palette = "Set1") +
  theme_bw()
```

Are there differences between the Adelie's based on the island?

```{r}
penguins %>% 
  filter(species == "Adelie") %>% 
  ggplot(aes(x = bill_length_mm, 
             y = bill_depth_mm, 
             color = island)) +
  geom_point(na.rm = TRUE) +
  scale_color_brewer(palette = "Set1") +
  theme_bw()
```
It looks random. What about flipper length?

```{r}
penguins %>% filter(species == "Adelie") %>% 
  ggplot(aes(flipper_length_mm,
             color = island)) +
  #geom_histogram(aes(y = ..density..)) +
  geom_density(alpha = 0.2) + 
  scale_color_brewer(palette = "Set1") +
  theme_bw()
```

Looks about the same.

```{r}
penguins %>% 
  ggplot(aes(flipper_length_mm,
             color = sex)) +
  #geom_histogram(aes(y = ..density..)) +
  geom_density(alpha = 0.2) + 
  scale_color_brewer(palette = "Set1") +
  theme_bw()
```

```{r}
penguins %>% ggplot() +
  geom_jitter(aes(x = year, y = body_mass_g, color = species, shape = sex)) +
  scale_color_brewer(palette = "Set1") +
  theme_bw()
```


```{r}

penguin_hues <- c("#e41a1c", "#377eb8", "#4daf4a", "#F2F0EB", "#636363", "#252525")

theme_penguin <- function() {
  theme_minimal() %+replace%
    theme(plot.background = element_rect(fill = penguin_hues[4], 
                                         colour = penguin_hues[4]),
          panel.grid = element_line(color = penguin_hues[4]),
          panel.background = element_rect(fill = penguin_hues[4], 
                                          colour = penguin_hues[4]),
          text = element_text(colour = penguin_hues[5]),
          plot.title = element_text(colour = penguin_hues[6],
                                    hjust = 0, size = 20, face = "bold"),
          axis.text = element_text(size = 10),
          plot.subtitle = element_text(hjust = 0, size = 13, lineheight = 1),
          axis.title = element_text(size = 10),
          axis.ticks = element_blank(),
          legend.position = "top",
          legend.justification = "left",
          legend.direction = "horizontal",
          legend.box.spacing = unit(0, "cm"),
          legend.text = element_text(size = 11))
}

penguins %>% ggplot(aes(x = bill_length_mm,
                        y = flipper_length_mm,
                        color = species)) +
  geom_point(na.rm = TRUE) +
  scale_colour_manual(name = "", 
                    values = c(penguin_hues[1:3]),
                    labels = c("Adélie", "Chinstrap", "Gentoo")) +
  theme_penguin()
```

We can classify the penguins using ^^^^ 


